package polimi.ascensore.network.message;

public enum MessageType {
    PLAYER_INFO_RESPONSE,
    SESSION_REPLACED,
    PONG,
    JOIN_GAME_RESPONSE,
    WAITING_ROOM_UPDATE,
    STARTING_GAME,
    HAND_UPDATE,
    BRISCOLA_UPDATE,
    PLAYER_STATE_UPDATE,
    SETTED_BET,
    PLAYED_CARD,
    TEXT_MESSAGE,
    END_ROUND,
    END_SET,
    PLAYER_EXIT_GAME,
    END_GAME,
    INFO_AFTER_RECONNECTION
}
